name: project_kim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # =========================
  # DATABASE
  # =========================
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

  # =========================
  # UTILITIES
  # =========================
  intl: ^0.19.0

  # =========================
  # EXPORTS (future ERP use)
  # =========================
  pdf: ^3.11.1
  printing: ^5.13.4
  excel: ^4.0.6

  # =========================
  # 📊 ERP ANALYTICS (NEW)
  # =========================
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true